Contain usage of nest-asyncio
jupyter/jupyter_client pull request #666
Opened 2021-07-09 14:41 UTC by SylvainCorlay

2021-07-10 08:21 UTC, davidbrochart approved these changes

2021-07-10 15:05 UTC, kevin-bates commented
Hi @SylvainCorlay.  The changes look good to me so far.  Prior to merge, could you please add a description that includes the reason for these changes and what impact they might have on existing applications that subclass or use `KernelManager` directly?  I suspect they too would need to move to `BlockingKernelManager`.  Given this will likely be slated for 7.x (correct?), I don't see that being an issue.

2022-02-18 00:56 UTC, IrfanJaya56 requested changes
>

2022-12-06 12:21 UTC, blink1073 commented
nest-asyncio usage was removed in #835

2022-12-06 12:21 UTC, closed without merging