add `AsyncKernelClient` to `doc/api/client.rst`
jupyter/jupyter_client pull request #819
Opened 2022-07-28 04:44 UTC by helioz11

2022-07-28 06:50 UTC, davidbrochart reviewed
Thanks @helioz11.
I'm wondering if it's worth adding the API of `AsyncKernelClient`, since it's the same as `BlockingKernelClient` except that it's async.
Maybe we should have the complete API for `BlockingKernelClient` and just say that `AsyncKernelClient` is identical but async?

2022-07-29 06:42 UTC, helioz11 commented
Sure, how about if I move the `automethod` from `AsyncKernelClient` to `BlockingKernelClient` and add extra information in `AsyncKernelClient`?

2022-07-29 07:01 UTC, davidbrochart commented
Yes, that sounds good.

2022-07-29 09:35 UTC, davidbrochart requested changes

2022-07-29 09:35 UTC, davidbrochart commented on docs/api/client.rst
> +   The available class methods are identical with :class:`BlockingKernelClient` but async.
```suggestion
   :class:`AsyncKernelClient` is identical to :class:`BlockingKernelClient` but the methods described above are async.
```

2022-07-29 09:51 UTC, davidbrochart approved these changes
Thanks @helioz11.

2022-07-30 08:39 UTC, merged